version: '3.8'

services:
  mortgage-postgres:
    image: postgres:13
    container_name: mortgage-postgres
    restart: always
    environment:
      POSTGRES_DB: mortgage
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

volumes:
  postgres_data:
    driver: local